### ISSUE TITLE
Range adjustement

### ISSUE THREAD

**Issue by mxmjnn** [mepster/wensn#1]
Hello,

I was wondering if anyone has looked into increasing the range that can be read. 

As of now it looks like the only usable ranges are "30-80", "40-90", "50-100" and "60-110". In the ranges list (wensn.py) 3 more options are listed: "70-120", "80-130", "30-130", and those 3 other levels are accessible when pressing the on sensor buttons, I am not able to set the sensor to read in the 30-130 range for example error: ValueError: "30-130" is not in list.

Other than this, am really stoked on using this tool thanks so much for publishing!

Best,

Maxime

**Comment by mxmjnn** [comment]
Just saw the comment regarding USB setting only accessing 2 bits of range. Still wondering if there is a workaround to this however.

**Comment by mepster** [comment]
Hi @mxmjnn yeah see the comment in the code, in the function setMode(). It seems to be a limitation of the device - you can set those higher ranges using the physical buttons on the device, but not over USB.

I did not have the source code for the device firmware - I was just reverse-engineering it - but that was my conclusion after a lot of playing with it.

However, this limitation is not such a big deal for monitoring because, although it does change the range shown on the device display, it doesn't change the sound levels returned over USB.

I have been logging continuously for more than a year with a Raspberry Pi, works great.

Cheers,

Mike

**Comment by mepster** [comment]
Access to the full range is fixed as of 705381e.
